# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad7ad13b9c9781b68c1c9ae17c16cf33adba923045abfa3ea0e8440ef87f53843045113333562843453c1147a37e65cd8bdddffc5a91ec28ba03caa4db44d766

test:
  secret_key_base: cd323f06759cf0efba107feaa92a24c6ff932800e87d094a5281e59386cfe01d4b0e0be20fcc56f56489b06c6d4d1a37d2896ff946faae81cf316121cdadafb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
